### PR TITLE
Fixed carousel images getting cut off or overlapping.

### LINKED ISSUE #134: Image carousel on front page broken for certain resolutions
The image carousel isn't centered for resolutions < 360px wide and the images get cut off for resolutions < 330px wide. This is a problem since 320px wide is still a reasonably common phone resolution.

The images also overlap and/or get cut off for all horizontal resolutions between 550px and 856px.
551px

### PR DESCRIPTION
**Pull request by robinlinden**
Images in the frontpage carousel no longer overlap or get cut off for some resolutions.
Fixes #134

### CODE REVIEW

**Comment by nurupo** [comment]
This PR breaks the carousel images on lower resolutions for me.

Before this PR

https___tox chat_

After this PR

http___localhost_

**Comment by nurupo** [comment]
That's using Chrome 54.0.2840.71.

**Comment by robinlinden** [comment]
There we go. I'll remember to test everything on Chrome next time I do a PR.

**Comment by nurupo** [comment]
Yep, looks good, will squash and merge.

For everyone else reading who missed the conversation on IRC about this PR: it fixes the image overrun only on the index page, the images are still overrunning in the Clients page, e.g. https://tox.chat/clients.html#toxygen-images, which is fine as we will soon have a carousel without these issues.

**Pull request merged**
