### PR TITLE
Update clients.html

### PR DESCRIPTION
**Pull request by dylhack**
Ricin supports Linux, Windows, OSX

### CODE REVIEW

**Comment by SkyzohKey** [comment]
@drhacko It also supports BSD ;)

**Comment by drhacko** [comment]
@SkyzohKey Fixed!

**Comment by SkyzohKey** [comment]
Thx, It could run on Android too, but would need to port gtk to it, or to rewrite the UI, so... Not supported c:

**Comment by tox-user** [comment]
Can you confirm that Ricin works on BSD OSes? On which BSD systems it has been tested? I might have to update my PR: https://github.com/Tox/tox.chat/pull/181

Recently we got this info from @aSourceFish:
> I could compile and run Konv (new version of Ricin) at OpenBSD, but I didn't test how it works. Maybe it may run, for example, at FreeBSD.

(https://github.com/Tox/tox.chat/pull/180#issuecomment-349176774)

**Comment by aSourceFish** [comment]
@SkyzohKey OpenBSD != FreeBSD != DragonFlyBSD != NetBSD. These projects' code's diverged over 20 years ago. Also Konv is problematic to compile because I have to guess by myself which dependencies to install. I've just successfully compiled and ran Konv at OpenBSD:

**Comment by aSourceFish** [comment]
@SkyzohKey https://i.imgur.com/6AYRBud.jpg
Also do you plan to update Konv?

**Comment by aSourceFish** [comment]
@SkyzohKey @tox-user anyway, I couldn't find a way to use text chat in Konv, clicking at avatars and names does nothing. Also Ricin won't compile:
$ ./waf configure 
Setting top to                           : /tmp/Ricin 
Setting out to                           : /tmp/Ricin/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'gobject-2.0'               : yes 
Checking for 'gthread-2.0'               : yes 
Checking for program 'valac-0.8'         : not found 
Checking for program 'valac'             : /usr/local/bin/valac 
Checking for valac version >= (0, 8, 0)  : (0, 38, 4) 
Checking for program 'msgfmt'            : /usr/local/bin/msgfmt 
Checking for program 'perl'              : /usr/bin/perl 
Checking for program 'intltool-merge'    : /usr/local/bin/intltool-merge 
Checking for header locale.h             : yes 
Checking for program 'glib-genmarshal'   : /usr/local/bin/glib-genmarshal 
Checking for program 'glib-mkenums'      : /usr/local/bin/glib-mkenums 
Checking for program 'glib-compile-schemas' : /usr/local/bin/glib-compile-schemas 
Checking for program 'glib-compile-resources' : /usr/local/bin/glib-compile-resources 
Checking for program 'valac-0.28'             : /usr/local/bin/valac 
Checking for valac-0.28 version >= (0, 28, 0) : (0, 38, 4) 
Checking for 'glib-2.0'                       : yes 
Checking for 'gio-2.0'                        : yes 
Checking for 'gobject-2.0'                    : yes 
Checking for 'gmodule-2.0'                    : yes 
Checking for 'gtk+-3.0'                       : yes 
Checking for 'libsoup-2.4'                    : yes 
Checking for 'json-glib-1.0'                  : yes 
Checking for 'libnotify'                      : yes 
Checking for 'libtoxcore'                     : yes 
Checking for library toxencryptsave           : not found 
The configuration failed
(complete log in /tmp/Ricin/build/config.log)
$

**Comment by SkyzohKey** [comment]
Ricin used an hack to check if the libtoxencryptsave did exists on the host system, because that lib do not has pkg-config files (`.pc`). So you can just edit the `wscript` file and it should work 😋

**Comment by SkyzohKey** [comment]
Oh and Konv/Ricin should run on ANY OS that can run C code, as Vala is just C-GObject syntactic sugar. :)

**Comment by tox-user** [comment]
The table on the bottom of this page https://tox.chat/clients.html says that Ricin doesn't work on Windows and Windows downloads for Ricin seem to be outdated: https://konv.im/downloads.html#windows. There aren't any Windows Ricin downloads on https://tox.chat/download.html. Are you sure it works on Windows :)?

According to @mazocomp's reports Ricin does not work on OpenBSD by default. If you want to say that it works on BSD it would be nice if you could find out on which BSD systems it can run. Then we would be able to put that info to this table https://github.com/Tox/tox.chat/pull/181.

**Comment by SkyzohKey** [comment]
Ricin is deprecated and I'm not going to add a single line of code to it. But it still does works Nice as a Tox client. You can compile it by looking at the wscript dependencies ;)

**Pull request closed without merging**
