### PR TITLE
Toxygen added

### PR DESCRIPTION
**Pull request by ingvar1995**

### CODE REVIEW

**Comment by nurupo** [comment]
@JFreegman so, toxygen is good to go?

**Comment by nurupo** [comment]
I will review the PR changes when I get a chance.

Just to speed the reviewing up, @ingvar1995 did you optimize the png files? [That is something I will look for when reviewing](https://github.com/Tox/tox.chat#contribution-guidelines). If not, I can suggest using `optipng -o7 -zm1-9 <filename>`, which will losslessly optimize png.

**Comment by ingvar1995** [comment]
done

**Comment by JFreegman** [comment]
@nurupo Looks good

**Comment by nurupo** [comment]
1. When I open the screenshots for Toxygen, it shows the very last screenshot instead of the first. It's because you have `checked="checked"` set on the 3rd screenshot, instead of the 1st -- fix that.

2. Also, squash commits into one and write a commit message that is more than one lowercase word. It seems there is no set rule for verb tense in commit messages and looking at the last few commits they use past tense, so "Added Toxygen" would work.

Other than that, it looks good.

**Comment by SkyzohKey** [comment]
> When I open the screenshots for Toxygen, it shows the very last screenshot instead of the first.

That's the messy slider fault ;)

**Comment by nurupo** [comment]
@SkyzohKey want to contribute a better non-js slider?

**Comment by ingvar1995** [comment]
@nurupo updated

**Comment by nurupo** [comment]
Looks good

**Pull request merged**
