### PR TITLE
Update uTox Win download links

### PR DESCRIPTION
**Pull request by redmanmale**
* update x64
* remove x86

### CODE REVIEW

**Comment by nurupo** [comment]
Also needs to be updated in `themes/website/static/js/osdetect.js`.

**Comment by nurupo** [comment]
What about the macOS build? uTox dropped macOS support?

**Comment by redmanmale** [comment]
>uTox dropped macOS support

No, we didn't.
Just haven't build latest macOS artefact... yet. Let's leave previous version for now.

**Comment by nurupo** [comment]
>No, we didn't.

After a short conversation on IRC it's clear that macOS is no longer supported due to lack of a macOS dev, so only Linux and 64-bit Windows are supported.

```
<nurupo> avoidr: did uTox drop macOS support?
<nurupo> the last few GH releases don't have .dmg file
<endoffile> nurupo: there isnt anyone that has a mac to build it
<endoffile> publicarray was building them but he hasnt been aroun in a little bit
<nurupo> endoffile: should i remove macOS dl uTox links from tox.chat then?
<robinli> Hasn't CeBe also built macOS releases? I don't recall. :x
<robinli> The main platforms we support are x86 and AMD64 Windows and Linux.
<robinli> Those are the platforms where the active devs can build and test uTox.
```

**Comment by nurupo** [comment]
Thanks!

**Pull request merged**
