### PR TITLE
small addons

### PR DESCRIPTION
**Pull request by zoff99**
* TRIfA
* java binding

### CODE REVIEW

**Comment by nurupo** [comment]
[Does TRIfA comply with TCS?](https://github.com/Tox/tox.chat#i-want-my-client-to-be-listed-on-your-website).

**Comment by zoff99** [comment]
the java binding is sperate from TRIfA.
i don't know if TRIfA does fully.

**Comment by zoff99** [comment]
i am not sure if any of the existing clients comply.
but this certainly will assure no client ever getting added to the website ever again.

**Comment by nurupo** [comment]
This assures that no client with bad client interoperability and bad security practices get added to the website.

**Comment by nurupo** [comment]
Anyway, you can't argue your way out of this one. Either your client complies with TCS and we add it, or it doesn't and we don't add it.

**Comment by zoff99** [comment]
as i said.

**Comment by zoff99** [comment]
also change the java/scala binding. the scala binding does NOT work with java. so this is an error on the website

**Comment by nurupo** [comment]
>who is "we"?

You and me. I can reword he sentence if you don't understand it, feel free to ask.

>also change the java/scala binding. the scala binding does NOT work with java. so this is an error on the website

A separate issue for discussing this would be appropriate.

**Comment by SkyzohKey** [comment]
@zoff99 Don't giveup, it took me forever to get Ricin on the website too ;)

**Pull request closed without merging**
