### PR TITLE
Removed command for all available packages because it hasn't worked

### PR DESCRIPTION
**Pull request by ovalseven8**

### CODE REVIEW

**Comment by installgen2** [comment]
@Zer0-One can you confirm this command's dysfunctionality first?

**Comment by ProMcTagonist** [comment]
Worked for me or I wouldn't have added it... You know it's only for Debian/Ubuntu with the Tox repo added, right?

**Comment by Zer0-One** [comment]
@ovalseven8 This command works just fine for me. Do you have any specifics on why it's failing for you?

**Comment by installgen2** [comment]
Unable to reproduce supposed bug, closing.

**Pull request closed without merging**
