### PR TITLE
Fix typo on About page

### PR DESCRIPTION
**Pull request by nurupo**
When revising the about page in #142 I didn't remove "is" that was there before and apparently none of the PR reviewers have noticed this. I have checked all my changes against a spellchecker, but it obviously didn't catch that as it's not a spelling error. You all know that I'm typo master and I'm not the best at English, so please proof-read my PRs more thoughtfully.

This issue was pointed out by someone emailing us.

### CODE REVIEW

**Comment by nurupo** [comment]
@optimumtact could you proof-read the rest of #142 too?

**Comment by nurupo** [comment]
@optimumtact fixed all the tings you have pointed out.

**Comment by optimumtact** [comment]
lgtm

**Comment by nurupo** [comment]
Ok, squashed commits.

**Pull request merged**
