### PR TITLE
Fixed up the css a bit.

### PR DESCRIPTION
**Pull request by robinlinden**
1. Replaced bootstrap.min.css with a non-minified version (for better gzipping) and removed ~50% of it since we're not using much of bootstrap. 
2. Merged fonts.css with style.css so we require fewer connections to the server on pageload.
3. Removed font support for IE8 and older. (For all fonts but the icon-font)
4. Removed deprecated prefixed CSS.

### CODE REVIEW

**Comment by nurupo** [comment]
Was `bootstrap.big.css` added by accident or you actually meant to add it? It doesn't seem to be used anywhere, so I wonder what purpose it serves.

**Comment by robinlinden** [comment]
I left it in for convenience if someone wants to use more of bootstrap
without googling for the code. I'm fine with deleting it.

**Comment by nurupo** [comment]
Keeping it is fine.

**Comment by nurupo** [comment]
Tested it, looks good to merge.

**Pull request merged**
