### PR TITLE
Updated download-page to include a developer section. (issue #130)

### LINKED ISSUE #130: can't find the link to the tox core git repo
I spent about 30 minutes to find the link to the tox core git repo. And still not pretty sure that this is an official one. It would be great (and obvious) to add this link to the Download section of the website. 

Thank you for great IM software :)

### PR DESCRIPTION
**Pull request by robinlinden**
Also added dark versions of plain.svg and unknown.svg as those icons looked alright as icon representing the developer section for now.
Fixes #130

### CODE REVIEW

**Comment by nurupo** [comment]
That's not a proper way to do this. The download page lists available client downloads by platforms: Windows, Linux, etc. What you did is add a new platform called "For Developers".

A proper way would be to add a separate "For Developers" section similar to the "All Platforms" section, but perhaps without the division on platforms and without the icons -- just a list of links to GitHub repositories.

**Comment by robinlinden** [comment]
Yeah, you're right. I wasn't thinking about how it only showed different platforms. I'm working on adding a new section instead. 

Are there any other GitHub repositories we should be linking to?

**Comment by SkyzohKey** [comment]
@robinlinden:
Ricin repo: https://github.com/RicinApp/Ricin
qTox repo: https://github.com/tux3/qTox
uTox repo: https://github.com/grayhatter/uTox
Toxygen repo: https://github.com/toxygen-project/toxygen
Toxic repo: https://github.com/JFreegman/toxic

Those are the main repositories, if u are lazy to search them all x)

**Comment by nurupo** [comment]
@SkyzohKey you seem to misunderstand what the "for developers" section should contain. You have listed repository of clients, and they should not be in that section. That section should list downloads that would allow you to develop applications using Tox, i.e. toxcore, its wrappers, etc.

**Comment by robinlinden** [comment]
Good thing @nurupo told me we should move it. It's way more semantically correct now. :) Should I go ahead and turn it into a list or keep it like so for now?
Desktop:
New For Developers-section
Phones:
For Developers-section on mobile

**Comment by robinlinden** [comment]
You mentioned wrappers and the like should be included. Should we wait until they ask to be included or just google it and include the notable ones?
E.g. https://github.com/Antidote-for-Tox/toxcore, https://github.com/JuliaIO/Toxcore.jl, and https://github.com/subliun/SharpTox?

**Comment by Impyy** [comment]
@robinlinden The correct repository for SharpTox is https://github.com/Impyy/SharpTox.

**Comment by SkyzohKey** [comment]
You can also find up-to-date Tox bindings for Vala here: https://git.ricin.im/Ricin/tox-vapis

**Comment by robinlinden** [comment]
So, how's this? Or just project names without the language?
Also, icons vs. no icons?

With icons
--
Without icons

**Comment by nurupo** [comment]
By "wrappers" I mean "language bindings", which the CocoaPods toxcore doesn't seem to be.

Rename "Wrappers" to "Toxcore bindings"

Here is a list of bindings to include, in alphabetical order:

- [C#](https://github.com/Impyy/SharpTox)
- [Go](https://github.com/codedust/go-tox)
- [Java/Scala](https://github.com/TokTok/jvm-toxcore-c)
- [Objective-C/Swift](https://github.com/Antidote-for-Tox/objcTox)
- [Python](https://github.com/aitjcize/PyTox)
- [Python](https://github.com/abbat/pytoxcore)
- [Vala](https://git.ricin.im/Ricin/tox-vapis)

I might have forgotten about some other bindings, I hope someone will open a PR later if it's so.

As for the "Toxcore" section, it would be nice to list:

- [irungentoo/toxcore](https://github.com/irungentoo/toxcore)
- [toktok/c-toxcore](https://github.com/TokTok/c-toxcore)

, since we have two toxcores now. Which also means that we need to remove the github icon in the footer, or maybe make it point to the repo of this website or Tox org? @JFreegman @GrayHatter what do you think should we do with the gh icon?

**Comment by GrayHatter** [comment]
Point it to toktok, if irungentoo would rather it point to his, he can start commiting again.

Meanwhile we're already fixing bugs and flaws, makes no sense to point to out of date code.

**Comment by robinlinden** [comment]
So here's what it looks like now, with the Toxcore GitHub link and the footer GitHub icon pointing to TokTok's repo.
List of language bindings and stuff.

**Comment by SkyzohKey** [comment]
@robinlinden Remove the icons and center the whole div to make it looks more clean and you'll be fine ;)

**Comment by robinlinden** [comment]
Bootstrap is quite convenient sometimes. :P 
tox

**Comment by SkyzohKey** [comment]
Also instead of displaying a big column list it would be better to put every binding on a single line, separated by comas. ie.

### ToxCore bindings
[SharpTox (C#)](#link), [go-tox (Go)](#link), [jvm-toxcore-c (Java/Scala)](#link), [objcTox (Objective-C/Swift)](#link), [pytoxcore (Python)](#link), [PyTox (Python)](#link), [Tox VAPIs (Vala)](#link), etc...

Including the name of the binding would be better to avoid conflicts ie. two python bindings, showing 2 times "Python" may leads to confusions.

That's all for me, anyway thanks for the work you already done :)

**Comment by robinlinden** [comment]
I agree with you on the `Name (Language)` thing. :P 

I'm not a huge fan of either long column or single wrapping line, though, so I'm not sure how to make that look good. 

Maybe `Language: Name0, Name1`? So for Python, it'd look like `Python: pytoxcore, PyTox`? Would shorten the list a bit and keep it in line with the style we used for e.g. listing different sources for Antox.

**Comment by SkyzohKey** [comment]
Hmm yeah could do the job if you lower the margins between lines (something like `margin: 5px 0;` should be sufficient i think) :)

**Comment by robinlinden** [comment]
Ah, that's why it looks so weird. I didn't notice that all other lists have style="margin-top: -15px" applied to each element after the first. :P Thank you!

**Comment by nurupo** [comment]
Include links to both toxcores I have mentioned in https://github.com/Tox/tox.chat/pull/131#issuecomment-257190880

**Comment by robinlinden** [comment]
@SkyzohKey added the link. I'm not sure about changing the title of the toxcore developer section from "Toxcore" to "Toxcore development repositories", though. What do you think?

**Comment by SkyzohKey** [comment]
@robinlinden I guess that should be fine, gives a bit more details about links, which is good for SEO.
@nurupo LGTM ! :)

**Comment by nurupo** [comment]
"Toxcore development repositories" -> "Toxcore"

Would be nice if we could put information icons at the end of each toxcore link, with popups/tooltips explaining the difference between irungentoo/toxcore and toktok/c-toxcore. It seems we use modal popup windows extensively, so I guess using them over tooltips would be proffered to match the rest of the website, maybe?

It's a bit hard for me to come up with the right wording, but for irungentoo/toxcore something along the lines of the following should be said:

>irungentoo/toxcore is the original Toxcore. This repository is not active because any change to Toxcore should be first reviewed and approved by irungentoo, as he is the only one who can merge changes, but irungentoo has been very busy lately and unable to find time to work on Toxcore. He only finds time to fix bugs in Toxcore. Also, this is the Toxcore most clients currently use, although not for long, as most clients are in the process of switching to toktok/c-toxcore.

and for toktok/c-toxcore:

>toktok/c-toxcore is a fork of the original irungentoo/toxcore. Toxcore developer, irungentoo, has been very busy lately and unable to find time to work on Toxcore. Because any change to Toxcore should be first reviewed and approved by irungentoo, as he is the only one who can merge changes, Toxcore development has been stalled for some time now. To get around this, a non-hostile Toxcore fork was created where the development is currently ongoing.

I'm pretty much repeated what https://blog.tox.chat/2016/08/update-new-client-xenial-packages-tox-in-google-play-toxcore-fork-and-more/ said.

**Comment by nurupo** [comment]
I don't think it makes sense to add incomplete Tox implementations like zetok/tox. This section is supposed to provide pointers for people wanting to develop with Tox, and there is not much you can do using an incomplete Tox implementation.

It might make sense to have a "Get Involved" page, which, besides all things, would include pointers for people wanting to help with the development of Tox-related things, which would list zetok/tox, but "Get Involved" page is out of scope of this PR.

**Comment by nurupo** [comment]
Also, there are more incomplete Tox implementations than just zetok/tox. There is hstox being worked on by iphy, I think there is also an Object-C/Swift implementation being developer by dvor, and there might be some more. None are complete as far as I know, correct me if I'm wrong.

**Comment by GrayHatter** [comment]
I started a python one a few months ago. But I agree with @nurupo none of them belong on the static site. That's what a community wiki page is for.

**Comment by SkyzohKey** [comment]
@nurupo Could you just merge this PR ? If fixes have to be made they'll be, but for now this PR is ready to merge, and waiting more could make it conflicting, so...

**Comment by nurupo** [comment]
@robinlinden Looks good, all that is left is to remove the unused `.svg` files and squash commits.

I'm also thinking if we should list TokTok/c-toxcore before irungentoo/toxcore. People are likely to click on the very first thing, and, well, there much is going on in irungentoo/toxcore.

@SkyzohKey I'm sorry, but I can't "just merge" until I test the changes and make sure that there is nothing that needs fixing. Not to mention that whenever something is merged, the website automatically pulls it and updates itself.
Also, if there are conflicts, you just need to rebase your changes. It's annoying, but that's how git works.

**Comment by nurupo** [comment]
@robinlinden Oh, it also appears to have commits from the Antox F-Droid PR. They shouldn't really be here.

**Comment by nurupo** [comment]
Ok, I see that we don't want to remove the `.svg` files. apparently some of our svgs were missing dark versions.

**Comment by nurupo** [comment]
Looks like @robinlinden was merging his own branches into this branch, instead of rebasing it against Tox/tox.chat's master. Looks like I was able to clean this mess a little. The only striking inconsistency is that 	aa50c1d despite its message also adds Rust bindings to the list, but that's fine.

**Comment by nurupo** [comment]
@robinlinden does this look good?

**Comment by robinlinden** [comment]
Yeah, sorry about the messy branch stuff. I've got a better handle on git now and it won't happen again. 
Your reordering of the list is fine, and I think this is ready to be merged.

**Comment by nurupo** [comment]
@robinlinden thanks for this PR, you really helped out.

**Pull request merged**
