### PR TITLE
Updated the Antox FDroid section with fingerprint & QR-code (issue 99)

### PR DESCRIPTION
**Pull request by robinlinden**
The QR-code with the url+fingerprint is currently base64-encoded since I had no idea of where you would like it placed if inlining it isn't alright.

### CODE REVIEW

**Comment by nurupo** [comment]
Where did you get this fingerprint from? The key we use for F-Droid has different fingerprint. It's SHA256: 9F:77:7D:D7:7C:7F:76:82:69:84:82:33:CF:83:D4:4F:5C:4F:E4:80:D7:D5:CB:1C:F3:28:20:B2:3A:1A:F0:86.

**Comment by robinlinden** [comment]
It's the fingerprint for the pubkey at the top of https://pkg.tox.chat/fdroid/repo/index.xml -- Sorry, I misunderstood what key you wanted the fingerprint for. I've committed a fix.

**Comment by optimumtact** [comment]
LGTM

**Comment by nurupo** [comment]
Looks good. Would be nice to display the fingerprint of our key too, like it's done at https://guardianproject.info/fdroid/, in capital letters with a space every 2 letters (this is also how F-Droid shows it to the user, so it's easier when both of them look the same).

**Comment by robinlinden** [comment]
Antox modal
@nurupo Like so?

**Comment by nurupo** [comment]
Yep, that's great.

If you are going to add a semicolon after "(SHA256)" it also makes sense to add one after "F-Droid app".

It should be good to merge after that.

**Comment by nurupo** [comment]
Looks good to me.

I was about to ask you to squash the 4 commits into 1, but I see GitHub has added "Squash and Merge" option for merging, so I will give it a try.

**Pull request merged**
