### PR TITLE
Update toxic binary download links to 0.12.0

### PR DESCRIPTION
**Pull request by JFreegman**

### CODE REVIEW

**Comment by Chiitoo** [comment]
Is the motivation for the repository move documented somewhere?

**Comment by JFreegman** [comment]
> Is the motivation for the repository move documented somewhere?

The TokTok repository is not being maintained

**Comment by Chiitoo** [comment]
Ah, thank you.  Thought a bit it was just qTox and others...  :\

**Comment by JFreegman** [comment]
> Ah, thank you. Thought a bit it was just qTox and others... :\
I just mean the TokTok/toxic repo. TokTok/c-toxcore is still being maintained, as well as toxic via my branch.

**Review by robinlinden — APPROVED** [review]

**Comment by Chiitoo** [comment]
Ah!  Thank you.  Very good.

**Pull request merged**
