### PR TITLE
Add PCLinuxOS download instructions

### LINKED ISSUE #161: Add PCLinuxOS download instructions
We have received a request from @marcin-82, the package maintainer of `qtox` and `toxcore` packages for [PCLinuxOS](https://distrowatch.com/table.php?distribution=pclinuxos) in main/official repository of distribution. You can see them in [this package repository mirror](http://ftp.nluug.nl/os/Linux/distr/pclinuxos/pclinuxos/srpms/SRPMS.pclos/).

Here are the instructions the maintainer has provided:

> You can install QTox on PCLinuxOS by two ways:
> I Synaptic package manager
> 1. Run Synaptic package manager and click "Refresh" to update
> repository indexes.
> 2. Search for "qtox" package and mark it for installation.
> 3. Click "Apply" and confirm installation.
> 4. Program will be available under "Internet" category in applications menu.
> 
> II Terminal
> 1. Run as root these two commands: 
> apt-get update
> apt-get install qtox
> 
> I'd like to format apt-get commands similar to BBCode - [code]text[/code] tags.
> 
> Here is logo of PCLinxuOS. I have approval/consent from Textar (Bill
> Reynolds - owner of PCLinuxOS trademark) to use it:
> https://pbs.twimg.com/profile_images/421896334/Aqua.png

### PR DESCRIPTION
**Pull request by tox-user**
Closes #161

Client download instructions for PCLinuxOS distribution.

### CODE REVIEW

**Comment by nurupo** [comment]
Looks good. Since `pclinuxos.svg` is your original work, what license is it under?

**Comment by tox-user** [comment]
CC BY-SA. Should I add that information somewhere?

**Comment by nurupo** [comment]
Hm, not too sure how licensing works here. When you contribute original code it's assumed that you license it to the same license the project is licensed under. I guess it's similar for assets too? Anyway, it would be nice if you mentioned it explicitly, like put a LICENSE file in `themes/website/static/img/dis/` with one-two lines containing the file name, author and license.

**Comment by tox-user** [comment]
What is the license for the rest of the images?

**Comment by SkyzohKey** [comment]
Nope. GPL is **NOT MADE** for assets. Assets (audio, video, graphics, etc) have their own licenses types (CC aka. Creative Commons) that are meant to be compliant with GPL while granting right based on the actual stuff being licensed.

**Comment by nurupo** [comment]
@tox-user I'd assume they are all CC-By-SA, like the LICENSE file says. I have no idea though, I got control of the website repository after all this was already added by the people who were previously managing it, I'm not even sure where other svgs come from, whether they were created from scratch for this website or they were taken from somewhere.

@SkyzohKey what are you talking about? No one suggests using GPL, no one has even mentioned GPL. Please don't post offtopic comments.

**Comment by tox-user** [comment]
@nurupo the project is licensed under CC BY-SA 4.0, including the code. I think that should mean that all of the art is licensed under CC BY-SA 4.0, unless specified otherwise? None of the imagines in dist folder contain a license in their metadata, expect for gentoo.svg:
```
Work Creator Agent Title        : Sebastian Pipping <sping@gentoo.org>
Work Rights Agent Title         : Lennart Andre Rolland, Gentoo Foundation Inc.
Work Publisher Agent Title      : Gentoo Foundation Inc.
Work Contributor Agent Title    : Lennart Andre Rolland for original vector version, idea for dark version and specific RGB value by unknown person
Work License                    : http://creativecommons.org/licenses/by-sa/2.5/
About                           : http://creativecommons.org/licenses/by-sa/2.5/
License Permits                 : http://creativecommons.org/ns#Reproduction
License Requires                : http://creativecommons.org/ns#Notice
```

We should probably have a separate license for the code?

**Comment by nurupo** [comment]
@tox-user oh, also, I have removed the distro-specific instructions from the Downloads webpage in https://github.com/Tox/tox.chat/pull/196, that's why you are getting a merge conflicts now. I was removing the Debian/Ubuntu package repository information before I actually shut down the package server, and I noticed that most of distro-specific instructions were not about how to get Tox from an official package repository of a distribution, but about Tox's own Debian, Ubuntu, [Arch](https://github.com/Tox/arch-repo-tox) and [Gentoo](https://github.com/Tox/gentoo-overlay-tox) repositories. Well, the Arch one also mentioned that Tox is available on AUR on the same page that it's talking about using Tox'es own Arch repo, that seems to be rather an exception. So I have removed mentioning of all Tox repositories, since none of them are being maintained, and placed "Please check in the package repository of your distribution." [on there](https://tox.chat/download.html), since nothing else was left and checking all distributions and their releases for Tox packages was out of scope of that PR.

**Comment by tox-user** [comment]
I see. What should we do about that then? Add a link for PCLinuxOS only? We could add links to build instructions there or each of the clients could have a short guide explaining how to build their client (they would have to update them) to make the panel not so empty.

Under Linux or GNU/Linux on the download page I would add:
PCLinuxOS / other

If we get more distros it would be:
Arch / Debian / PCLinuxOS / Ubuntu / other

That's how I list them currently based from JSON (don't remember if it's in one of the PRs). All of the links would open the same panel like they used to. "other" would be a tab that contains compilation instructions.

**Pull request closed without merging**
