### PR TITLE
add link to digital ocean

### PR DESCRIPTION
**Pull request by stal888**
needs rubber-stamping by any of @JFreegman @nurupo

### CODE REVIEW

**Comment by JFreegman** [comment]
Rubber stamped

**Comment by nurupo** [comment]
kxwoq 51 45

I don't understand why it's grouped along with social media buttons. Might make more sense to add bigger left margin or maybe even pull it to the right side instead, to the CC block.

**Comment by stal888** [comment]
@nurupo A margin has been added 
screen shot 2016-03-21 at 22 08 35

**Comment by nurupo** [comment]
It's okay.

**Pull request merged**
