### PR TITLE
Downloads page redesign

### PR DESCRIPTION
**Pull request by ingvar1995**
Few screenshots:

### CODE REVIEW

**Comment by ingvar1995** [comment]
@nurupo ping

**Comment by nurupo** [comment]
Sorry, been somewhat busy lately.

It looks good, but some things need to be improved:

1. With javascript disabled, I don't get the list of distributions for Debian/Ubuntu, I get generic instructions for uTox (even though I selected Toxygen) using `$(lsb_release -cs)`.

  no-js-1

2. With javascript enabled, I don't see an option to use stable packages or nightly packages, it gives instructions for nightly straight away. For example, Ricin is available only in stable package repository, so the package instructions should show only instructions for the stable package repository. Toxygen is available in both stable and nightly package repositories, so a user should select which instructions to see.

  yes-js-instructions-1

3. Some download instructions are missing, e.g. Antox F-Droid.

**Comment by ingvar1995** [comment]
1. Nothing can be done without duplicating html 
2. Will fix it
3. Antox F-Droid, what else? If you see something missing, you can open pr to my fork with fix

**Comment by ingvar1995** [comment]
@nurupo any update on this? if no, i will close this PR

**Comment by nurupo** [comment]
Haven't had the time to look at it. Why close though, do you not want this to be merged?

**Pull request closed without merging**
