### PR TITLE
Add yaourt example for arch

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by anoadragon453** [comment]
What if the user doesn't have or know what `yaourt` is?

**Comment by benwaffle** [comment]
I think most arch users use yaourt

**Comment by anoadragon453** [comment]
True, although `yaourt` isn't the only method of accessing the AUR. Perhaps just mention it's available in the AUR with a [link](https://aur.archlinux.org/packages/utox/) to it?

**Comment by benwaffle** [comment]
I don't think a link will be helpful for new users. Antergos and Manjaro (arch-based distros) come with yaourt and those who already know how to use the AUR can probably figure out how to make it work with their AUR helper.

**Pull request merged**
