### PR TITLE
add buildsite.py for translations

### PR DESCRIPTION
**Pull request by stal888**
it's good

### CODE REVIEW

**Comment by esprimo** [comment]
It looks good but I think it still won't work if you check out issue #10 the wish is to have no backend, which this seems to require, or is it just something you compile? How is it supposed to be used?

Also, I noticed you changed some texts. I don't have anything against it but it's not mentioned anywhere so more of an FYI for others.

**Comment by installgen2** [comment]
Not merging this, fixing my translations engine instead, keeping this PR open to remind myself.

**Comment by installgen2** [comment]
Nevermind, pretty sure this must be a different version to what you showed me before because it's not so shit... I'll merge this soon.

**Comment by stal888** [comment]
lel

**Comment by stal888** [comment]
@esprimo buildsite generates static HTML for the server. There is no backend.

And the changed strings wasn't intentional, I think I extracted them from an old version...

**Comment by Zer0-One** [comment]
@stal888 were you going to fix this up at some point?

**Comment by stal888** [comment]
all in good time my friend

**Comment by Zer0-One** [comment]
@stal888

**Comment by stal888** [comment]
Hello

**Pull request merged**
