### PR TITLE
Fix length of seperator's on clients page.

### PR DESCRIPTION
**Pull request by anoadragon453**
Thanks for @RowenStripe for fix.

#59

### CODE REVIEW

**Comment by installgen2** [comment]
No changes to bootstrap.min.css pls, can you fix this in another way?

**Comment by anoadragon453** [comment]
Yeah, lemme look into it.

**Comment by anoadragon453** [comment]
Alright, bootstrap unaffected, just made a separate separator style.

**Comment by installgen2** [comment]
Is the hr-long class universal? Or specific to this use case.

**Comment by anoadragon453** [comment]
It's a quick-fix to bypass Bootstrap's -15px rule for <hr>.

**Comment by installgen2** [comment]
But isn't that rule only for the contents of containers?

**Comment by Zer0-One** [comment]
@installgen2 what's the status on this?

**Comment by installgen2** [comment]
@Zer0-One I don't like this PR, see last comment.

**Comment by anoadragon453** [comment]
I've been meaning to fix this one up for a while, it is sort of a dirty hack. I'll take a look at revising it hopefully tonight.

**Comment by anoadragon453** [comment]
Closing in favor of #79's solution.

**Comment by RowenStipe** [comment]
Sorry XD

**Comment by anoadragon453** [comment]
@RowenStipe No worries, this solution was a hack anyways :P

**Pull request closed without merging**
