### PR TITLE
Design fine-tuning and some minor CSS structure changes

### PR DESCRIPTION
**Pull request by esprimo**
* Changed sizes, weights, margins, etc to make the site airy/less tight. 
* Added window decoration to the desktop screenshot.
* Removed "Learn more" (can be added again, CSS is still there) since it doesn't do anything at the moment

I also made some minor changes to how the CSS is structured to make it easier to change. That part still needs more work on the whole document since I only did that for the parts I change now.

It's easier to see the changes in full screen mode.

Before:
image

After:
image

### CODE REVIEW

**Comment by Zer0-One** [comment]
@esprimo I definitely would have preferred smaller PRs (and @installgen2 may ask you to split this), but let me outline what I think is good and bad here.

Good:
1. I like the smaller fonts

Bad:
1. The "Learn More" button is going to do something very soon, I'm not sure why you bothered removing it.
2. That image you modified is a mockup, and is going to be replaced very soon with a few real client images.
3. In sections where you decreased the font size, you didn't decrease the size of the section; there's too much empty vertical space.
4. You removed the icon from the "Download" button, and re-named it

I'm not familiar enough with CSS to comment on your structural changes, @installgen2 will have to go over that.

**Comment by esprimo** [comment]
Sounds fair. I chatted with @installgen2 a few months ago and showed him "this" layout/design by then but never bothered to finish it and make a PR. Seems he took inspiration from it and made some of the things I had in that suggestion so today I just kind of made changes to make it look more like the one I showed before.

This is what I had before btw: https://imgur.com/vf5gr4d.

I see your point about big PRs tough and thanks for the rest of the feedback. I'll try to answer for the bad things at least:

1. As the commit message said: the CSS is still there and personally I don't really see any point of having the HTML there if it's not used at the moment. Then it should be in a different branch or something until it's done.
2. I didn't modify the image but rather added CSS to make it look like it had window decorations (border+shadow). It works for all images/screenshots, given the screenshots don't already have window decorations in them (which they IMO shouldn't have, the focus is supposed to be on the application, not the window manager).

**Comment by installgen2** [comment]
Can't test it out right now, but after a brief look at the code I noticed some font-weight changes, are these working on all platforms? We don't include all of the different font weights so it's possible it is only working on your computer as it may have the font installed locally. Also, what's with the double "--"s?

**Comment by esprimo** [comment]
@installgen2 Yes, the font-weights should work. I use font-weight 200 which is included. That being said, I've only tested it on linux/Ubuntu 15.04.

The double "--"s comes from a widely used CSS naming convention for HTML/CSS. You can read more about it here: 
* https://css-tricks.com/bem-101/
* http://getbem.com/introduction/
or just google "BEM CSS" or something. 

**Td;dr** use double dashed for naming style modifiers on an object and use double underscores to name dependent children. 

Example for properties:
* `.button--red` would be a button that is red
* `.button--green` would be a green button
* `.button--big` could be a button that is bigger than the standard one

Example for children:
* `.list could` be an ul or ol
* `.list__item` could li and would be a child of `.list`

It's okay if that's not something you like but I think it's good to use known and tested methonds for development, it makes it easier for new people to join and the code more consistent. 

If you're okay with BEM/ant to check it out I can make another PM where I've rewritten the entire site to use this naming convention. It's probably easier to see the benefit in that case.

**Comment by ProMcTagonist** [comment]
Many pieces of text are too small/light. Readability is important.

**Comment by esprimo** [comment]
@ProMcTagonist Thank you for the feedback! Could you specify which parts you're referring to?

The text is indeed smaller but I don't think that will be a problem. The smallest size I use is 15px, which is bigger than the standard font size in gmail for example. I'm not sure if the screenshot is scaled down but the text in the screenshot seems to have about the same text size, if not even smaller.

A bigger problem, IMO, with readability is the contrast of the yellow button and the white text in it, and the paragraph color on the grey sections or what do you think about that?

**Comment by ProMcTagonist** [comment]
> Could you specify which parts you're referring to?

The orange title texts, "What Makes Tox Different" + "A New Kind of Instant Messaging" stood out and looked better when heavier, IMO.

> The smallest size I use is 15px, which is bigger than the standard font size in gmail for example.

Alright, cool. It's not bad at all fullsized, my bad.

> the contrast of the yellow button and the white text in it

Maybe darken the text shadow/orange?

> and the paragraph color on the grey sections

Could make it heavier or darker. 

The whole site should go through colorblindness filters before it's finished.

**Comment by installgen2** [comment]
The lack of download icon makes me cry, and the non-fixed download button width makes the downloads page look ugly. When you have 2 download buttons on the downloads page with text different lengths, they will now have different button widths, can you implement a fix for this?

**Comment by esprimo** [comment]
@installgen2 I'm not sure if I'm misinterpreting what you're saying. I only see one download button on the download page, does it depend on which OS I run or something? (aka. how do I reproduce?)

I'll re-add the download icon, I don't want people to cry!

And do you agree with @ProMcTagonist, should I make the heads fatter again? Personally I think it's much better looking when they're thin.

**Comment by ProMcTagonist** [comment]
> I only see one download button on the download page, does it depend on which OS I run or something? (aka. how do I reproduce?)

Yes.

Get a user agent changing extension and enable javascript.

**Comment by esprimo** [comment]
The download buttons on the download page now has fixed with. Anything else that's needed?

**Comment by anoadragon453** [comment]
I can understand trying to hide the "Note: Tox is still under heavy development — expect to run into some bugs.", but do remember it's important for users to not think this is the final, end-all product we're presenting here. 

Might want to make the text a bit lighter so it's readable on the dark-grey background.

**Comment by Zer0-One** [comment]
I'm still against the added empty vertical space, but I'll go with whatever @installgen2 decides.

**Comment by esprimo** [comment]
@anoadragon453 I don't think I changed that actually, but it\s a good point and something that should be fixed in a future PR probably. Maybe add an issue about it?

**Pull request closed without merging**
