### PR TITLE
Converted to use Pelican static site generator

### PR DESCRIPTION
**Pull request by nurupo**
It's rather inconvenient that when you want to edit the footer, you have to edit it in all of the HTML files as each of them contains a copy of it. It's easy to make a mistake doing so, which was already proved before https://github.com/Tox/tox.chat/pull/92, and, frankly, it's quite tedious. Using a template language for our website would solve this as it, along with many other helpful features, allows for one instance of HTML to be automatically inserted into many files.

Since our website is static, I have looked into available static website generators. The following search criteria was used to evaluate static site generators

- Being able to generate general purpose websites, not just blogs
- Have good documentation and examples
- Have a reasonably sized community
- Support i18n
- Have small installation footprint (including dependencies)
- Be in Debian package repository
- Use a language that is quite common and easy to pick up

[Pelican](http://docs.getpelican.com/en/latest/index.html) was chosen as the static website generator as it met all of the criteria. In fact, even the [Jinja2](http://jinja.pocoo.org/), which is the library for Jinja2 template language used by Pelican, meets all of the criteria, but the Pelican was selected over bare Jinja2 as using Jinja2 library would require some boilerplate code to be written, which is already done in Pelican, and Pelican has quite a few helpful plugins, for example [i18n_subsites](https://github.com/getpelican/pelican-plugins/blob/master/i18n_subsites/) and [assets](https://github.com/getpelican/pelican-plugins/tree/master/assets), which in themselves are boilerplate codes for getting Jinja2 [i18n](http://jinja.pocoo.org/docs/dev/extensions/#i18n-extension) and [assets](http://webassets.readthedocs.io/en/latest/integration/jinja2.html) extensions to work that we otherwise would have to write ourselves. It's also possible to use Pelican for the blog, which would allow the website and the blog share the same templates / web design, if we chose to get away from using WordPress at some point. However, since we don't use any blogging functionality Pelican provides, we can think of it as a boilerplate on top of Jinja2 for now.

This PR converts our website to use Jinja2 templates and Pelican static website generator. There are a few changes that were done to the website

- Title of main page says "A New Kind of Instant Messaging" and titles of supplementary pages say "\<page name\> - Tox", e.g. "About - Tox", when all pages said "A New Kind of Instant Messaging" before
- Assets (css, js, images, fonts) are moved into `themes` subdirectory as this is what Pelican does
- Removed symbolic links to pages

### CODE REVIEW

**Comment by nurupo** [comment]
Don't merge this PR, as it would break out current website if the server-side is not setup correctly. I will merge it myself after enough people approve it.

**Comment by SkyzohKey** [comment]
:+1 :

**Comment by nurupo** [comment]
@JFreegman @Impyy @stal888 how does this look? Also check if that is correct https://github.com/nurupo/tox.chat/blob/a143552d7b96b9bc52661381cfa1943470c612bb/README.md#i-want-my-client-to-be-listed-on-your-website

With this, we can easily make the site multilingual using GNU gettext and use Markdown for long text parts, like the ones in FAQ. Multiple language support and markdown support are not in the PR though, mostly because we need to update website's content before translating.

**Comment by nurupo** [comment]
https://tox.chat/beta/ . Pretty much the same as the current website besides the 3 points pointed out at the end of the opening post.

**Comment by Impyy** [comment]
LGTM

**Comment by stal888** [comment]
What would a translator do to put a new language on the site?

**Comment by nurupo** [comment]
Use Weblate or whatever service we decide to use. They could also edit the .po files directly and send a PR.

**Comment by nurupo** [comment]
Ok, looks everyone likes this PR so I will be merging it (server side is handled).

**Pull request merged**
