### PR TITLE
qTox version bump

### PR DESCRIPTION
**Pull request by nurupo**
CC @sudden6

### CODE REVIEW

**Comment by sudden6** [comment]
lgtm

What do you think about a link to our official flathub.org repository? https://flathub.org/apps/details/io.github.qtox.qTox

It would provide automatic updates.

**Comment by nurupo** [comment]
@sudden6 I thought you didn't want to advertise Flatpak yet until the video issue is resolved? Anyway, added it in the 3rd commit.

**Comment by sudden6** [comment]
@nurupo video issue is solved :)

Thanks.

**Comment by sudden6** [comment]
@nurupo can you wait a bit, we are working on v1.16.2 to fix an annoying bug.

**Comment by nurupo** [comment]
Bumped to v1.16.2.

**Comment by nurupo** [comment]
Should I wait on 1.16.3 and bump to that? I see a tag for 1.16.3 was pushed 4 hours ago, without any build artifacts though.

**Comment by nurupo** [comment]
Alright, rebased everything to use v1.16.3 now that it got build artifacts, should be good to go.

**Comment by nurupo** [comment]
The Linux download section is getting a bit ugly, but nothing I can do about it :\ Maybe once we get the website update PR merged we will look into ways to improve it, like the tox-user's closed PR.

**Pull request merged**
