### PR TITLE
Updating Antidote screenshots, adding Antidote to main page

### PR DESCRIPTION
**Pull request by dvor**

### CODE REVIEW

**Comment by nurupo** [comment]
What is the PIN screenshot supposed to mean?

**Comment by robinlinden** [comment]
Right now you're missing a radiobutton to toggle between the images and some css.  

See the desktop-slider div: https://github.com/dvor/tox.chat/blob/310c4908794522d0df46637b52ecd8bed8d0d3ec/themes/website/templates/index.html#L26:L31
And for the CSS you can copy this: https://github.com/dvor/tox.chat/blob/310c4908794522d0df46637b52ecd8bed8d0d3ec/themes/website/static/css/style.css#L218:L221 and change the IDs to `#mobile-images-control1` and 2.

**Comment by nurupo** [comment]
Any update on this?

**Comment by dvor** [comment]
Sorry, I'm currently out of time. Will try to update pull request in a few days.

**Comment by nurupo** [comment]
That's fine, just making sure you didn't forget about it.

**Comment by Kcchouette** [comment]
so you can close this one following #217

**Pull request closed without merging**
